### ISSUE TITLE
[Feature Request]: Make Length type a functor

### ISSUE THREAD

**Issue by rolandpeelen** [reasonml-labs/bs-css#169]
Imagine the following scenario:

```ocaml
module base = {
  paddingX: 2.0 -> rem,
  paddingY: 1.0 -> rem,
}
```
I think it would be really nice to do the following (instead of using `calc(add)`)

```ocaml
let someStyle = style([
  paddingLeft(base.paddingX -> map(double));
  paddingRight(base.paddingX -> map(half));
]);
```

**Comment by giraud** [comment]
Hi, I don't understand what you're trying to solve, can you elaborate ?

**Comment by rolandpeelen** [comment]
Hi @giraud 

Thanks for answering! I would ideally have static values in there, but based on some base value that kind of works as an interval. 
Let's say my base padding value is 0.5rem. Maybe I want a button that has double that spacing. Or triple. But I don't want to hardcode those values. If I could map over the value inside the type, and provide a function to calculate the new padding based on the old one (without using that `calc` syntax), I can just update one value later on if we want slightly more or slightly less spacing.

I could create a PR that would have a somewhat naive version of this so you can see what I mean?

**Comment by giraud** [comment]
If I have that code:
```

module Base = {
  let paddingX = 2.0;
  let paddingY = 1.0;
  let map = (x, fn) => fn(x);
  let double = x => x *. 2.0;
};

open Base;

let someStyle = Css.(style([padding2(~h=paddingX->rem, ~v=paddingY->rem)]));

let someStyle1 = Css.(style([padding2(~h=paddingX->map(Base.double)->rem, ~v=paddingY->rem)]));
```

it produces the following code:

```
var someStyle = Css.style([Css.padding2(Css.rem(1.0), Css.rem(2.0)), 0]);
var someStyle1 = Css.style([Css.padding2(Css.rem(1.0), Css.rem(2.0 * 2.0)), 0]);
```

is it close to what you're describing?

For me this is something that should be done outside the lib. I'd like to avoid introducing an unneeded complex structure like a functor, and I don't feel that it belong to the core value of this lib.

**Comment by rolandpeelen** [comment]
@giraud - Thanks for your reaction!

Yes, this comes very close to what I would want. However, I would be very keen to also have the actual type in my configuration (ie. `2 -> rem` instead of just `2.0`) so the map function would have to do slightly more. To me, this is very tightly bound to the type definition and I would not necessarily agree it's an unneeded complex structure (ie. we can just provide the map function for the user);

```javascript
map(value, fn) {
  switch value{
    | `ch(floatVal) => fn(floatVal) -> ch
    | `em(floatVal) => fn(floatVal) -> em
    | `ex(floatVal) => fn(floatVal) -> ex
    | `rem(floatVal) => fn(floatVal) -> rem
    | `vh(floatVal) => fn(floatVal) -> vh
    | `vw(floatVal) => fn(floatVal) -> vw
    | `vmin(floatVal) => fn(floatVal) -> vmin
    | `vmax(floatVal) => fn(floatVal) -> vmax
    ...
  }
}
```
It's not pretty and perhaps we can find a way to have it wrapped back into its own value a little less verbose, but it does make for an extremely simple way to map to the values inside of these things.
I've currently written something similar for the Color type, to darken / lighten them (ie. have similar utility functions as one would have in SASS).

I personally feel this should be inside / near the type definition. If not, perhaps we can make a separate repo that holds these map functions in a separate module namespace and we refer from bs-css to that?

**Comment by giraud** [comment]
I was worried because you talked about transforming the type to a Functor as explained in https://v1.realworldocaml.org/v1/en/html/functors.html, and this is not a lightweight structure. But I think it's more like transforming the type to a list monad (sort of).
I stil don't understand why it is useful, but you could create a PR so we can see what changes are needed to the code.

**Comment by rolandpeelen** [comment]
@giraud -- I don't think that will be necessary, just exposing the map function should be enough :). I'll try and make a PR somewhere next week
