### ISSUE TITLE
Percent is missing factory function

### ISSUE THREAD

**Issue by TomiS** [reasonml-labs/bs-css#178]
There is percent polyvariant here:
https://github.com/reasonml-labs/bs-css/blob/fa3518cdf38d9dbcd53a83db837c8fe241420166/src/Css_AtomicTypes.rei#L73
but not a corresponding function here
https://github.com/reasonml-labs/bs-css/blob/fa3518cdf38d9dbcd53a83db837c8fe241420166/src/Css_AtomicTypes.rei#L104-L109

**Comment by eWert-Online** [comment]
You can use it with `pct()` like this: `width(100.0->pct)`

**Comment by TomiS** [comment]
Hmm.. so it seems. Somehow I've been able to miss that. So I guess it's not a mistake then, so I'll close this. Thanks!
