### ISSUE TITLE
bs-css-emotion needs bs-css in bsconfig dependency

### ISSUE THREAD

**Issue by paulshen** [reasonml-labs/bs-css#181]
When I upgraded to `bs-css-emotion` (bs-css v12), I needed to also add `bs-css` to my `bsconfig.json`. Otherwise, I got the following error. The [README](https://github.com/reasonml-labs/bs-css/tree/17b270ba850a4799989a0ae66892e4a4b44d478e#installation) implies only "bs-css-emotion" is needed.

```
  This has type:
    [> Css.Types.Color.t ]
  But somewhere wanted:
    Css.Types.Color.t (defined as Css_AtomicTypes.Color.t)
```

and

```
Error: This expression has type [> Css.Types.Color.t ]
       but an expression was expected of type
         Css.Types.Color.t = Css_AtomicTypes.Color.t
Css.Types.Color.t is abstract because no corresponding cmi file was found in path.
```

Adding `bs-css` to my `bs-dependencies` fixes it. I don't know if this is an issue with BuckleScript (I'm on 7.1.1) but reporting here in case it helps other.

```
"bs-dependencies": [
  "bs-css",
  "bs-css-emotion",
  ...
],
```

**Comment by giraud** [comment]
I've tested from a clean project, and only bs-css-emotion is needed to compile the code.
Maybe there is a cache problem ?

**Comment by paulshen** [comment]
I believe it could be something locally! I was able to consistently repro locally so I documented steps here in case. Cloning this repo (bs-css) and running the example in `bs-css-emotion/` directory works for me.

Here are the steps to repro with a new project.

- `bsb -init bs-css-test -theme basic-reason`
- `yarn add bs-css-emotion`
- Add `"bs-css-emotion"` to `bs-dependencies`
- Try using the library. https://github.com/paulshen/bs-css-test/blob/c3902a5d38143078488e28971bd2280cd1954141/src/Demo.re

Here's a repo that reproduces the error https://github.com/paulshen/bs-css-test I get the following build error.

```
  We've found a bug for you!
  /Users/paulshen/Code/bs-css-test/src/Demo.re 2:24-36

  1 │ {
  2 │   Css.(backgroundColor(hex("000000")));
  3 │ };

  This has type:
    [> Css.Types.Color.t ]
  But somewhere wanted:
    Css.Types.Color.t (defined as Css_AtomicTypes.Color.t)

FAILED: subcommand failed.
```

If cloning this repo and running it (`yarn` then `yarn build`) doesn't repro, then it's a local issue.

**Comment by giraud** [comment]
thank you for that report, I'll look at it

**Comment by giraud** [comment]
you're right, something's wrong with module include.
I tested with display property and this one has no problem :(

**Comment by cuevash** [comment]
Yes, I am having the same problem. Adding  `bs-css` to the `bsconfig.json` file solves the problem.

**Comment by giraud** [comment]
at least, there is a simple workaround until that problem is fixed.

**Comment by giraud** [comment]
transitive dependencies are not handled by bucklescript, they all need to be explicit and direct. README updated.
