### ISSUE TITLE
Is there a way to add custom css selectors?

### ISSUE THREAD

**Issue by JasoonS** [reasonml-labs/bs-css#189]
For example, would it be possible to add this inline in my reason code?

```
    button::-moz-focus-inner {
      border: 0;
    }
```

I'd be happy to document this and PR when I learn how.

**Comment by brad-decker** [comment]
```reasonml
let mozFocusInner = selector("::-moz-focus-inner");
```
You can then use mozFocusInner like you would 'hover' or 'after'

**Comment by giraud** [comment]
you can find all selectors here https://github.com/reasonml-labs/bs-css/blob/master/bs-css/src/Css_Core.rei#L1009

**Comment by JasoonS** [comment]
Thanks, I'll give this a try tomorrow!
