### ISSUE TITLE
HSL/HSLA color API behaves counter-intuitively

### ISSUE THREAD

**Issue by TomiS** [reasonml-labs/bs-css#194]
In HSL color spec saturation (S) and lightness (L) fields are percentage values. Those are correctly typed [in here](https://github.com/reasonml-labs/bs-css/blob/v12.2.0/bs-css/src/Css_AtomicTypes.rei#L514-L519)
However the factory functions [a few rows below](https://github.com/reasonml-labs/bs-css/blob/v12.2.0/bs-css/src/Css_AtomicTypes.rei#L528-L530) accept just floats. The actual types being percentages, one would expect that the pure float values are in range from 0.0 to 1.0. This is not how it works here though. To get the correct CSS value `hsl(112deg,100%,10%);`, one needs to write like this:
```
hsl(deg(112.0), 100.0, 10.0) // <- unexpected, isn't it?
```
The same written correctly (imho) would be either:
```
hsl(deg(112.0), 1.0, 0.1)
```
or by using already existing types
```
hsl(deg(112.0), pct(100.0), pct(10.0))
```
Personally I would prefer the latter one.

**Comment by giraud** [comment]
right. this will be a breaking change.

**Comment by TomiS** [comment]
Yep, unfortunately it will. But better now than two years later :)

**Comment by TomiS** [comment]
@giraud Oh, just noticed something else too. If you look at the `rgba` function [a few rows above](https://github.com/reasonml-labs/bs-css/blob/v12.2.0/bs-css/src/Css_AtomicTypes.rei#L527), it has a signature of `(int, int, int, float)` and the float is also a percentage value that works correctly in the range 0-1 at least based on the test I saw in your commit. Just wanted to bring this out before tagging as it's a potential consistency issue I didn't notice before.

I guess the purpose of these functions is to provide as easy as possible way to create the variables, which would support using primitives like in `rgba`. On the other hand, the hue `angle` in HSL(A) cannot be expressed sensibly without accurate type anyway (is it deg or rad? Who knows...) so maybe it's best to have also the percentages like you implemented them in your commit even if it's not quite consistent with how `rgba` works. I don't know...
