### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by vmarcosp** [reasonml-labs/bs-css#196]
What do u think to create a documentation using docusaurus like [Reform](https://astrocoders.dev/reform/)?
I think that just the readme.md it's not the best approach to document a library like `bs-css`. I can help with this making a logo proposal and creating the documentation website.

**Comment by giraud** [comment]
Hi, I think that's great, but I personally can't create nor maintain it

**Comment by vmarcosp** [comment]
No problem @giraud, i can help you. Can we use this issue to discuss the details about the logo and the documentation?

**Comment by giraud** [comment]
yes, sure.
