### ISSUE TITLE
[Feature Request] stroke-dasharray for SVG

### ISSUE THREAD

**Issue by pzshine** [reasonml-labs/bs-css#206]
As I've used this property for making an animation on SVG circle, it needs to use `stroke-dasharray` to make it happens.
So I used `unsafe("stroke-dasharray", "0 100")`, it was very unsafe as the name, and the browser console keeps showing this message.

![image](https://user-images.githubusercontent.com/17017699/91876545-02452180-eca7-11ea-8cf2-855ddf6d28bd.png)

Would you mind to suggest to me what I can remove this or add this property in `bs-css`?

Thank you

**Comment by giraud** [comment]
Hi, PR is welcome.
you can find the svg properties in Css_Core.rei in the SVG module.

**Comment by lucasweng** [comment]
hi @pzshine,

Writing css properties in camel case will fix that error, like `unsafe("strokeDasharray", "0 100")`

The `Css.style` uses emotion's [object styles](https://5faaafd0bd0f3f0008469537--emotion.netlify.app/docs/object-styles) under the hood

https://github.com/reasonml-labs/bs-css/blob/c21a693b9472853e41ec7596ffba09736bf09aba/bs-css/src/Css_Js_Core.re#L32

`toJson` turns style rules into a JSON object
https://github.com/reasonml-labs/bs-css/blob/c21a693b9472853e41ec7596ffba09736bf09aba/bs-css/src/Css_Js_Core.re#L24-L25

`CssImplementation.make` is defined here
https://github.com/reasonml-labs/bs-css/blob/c21a693b9472853e41ec7596ffba09736bf09aba/bs-css-emotion/src/CssJs.re#L8
