### ISSUE TITLE
Emotion 11 and dependency structure

### ISSUE THREAD

**Issue by TomiS** [reasonml-labs/bs-css#223]
For some time already I've been aware that `bs-css-emotion` has a dependency on `emotion` instead of `@emotion/core` and other sub packages that [are recommended when using Emotion with React](https://5faaafd0bd0f3f0008469537--emotion.netlify.app/docs/install). We're using those sub packages in our app, so this has been slightly awkward as I'm not 100% confident that there can be no duplicate emotion instance problems in some situations when `emotion` package is in use too. In any case, I realized that for example `cx` function was not available in any of the version 10 sub packages (afaik), so using those in bs-css was not really an option.

When going through Emotion docs, I realized this is no longer a problem in version 11. It seems that the new Emotion API in version 11 is much better structured than in version 10 and it also provides a proper `cx` function again. Also `css` function now generates className strings and not the special kinds of objects it used to generate. This means that it could be possible to change the `bs-css` bindings to target the sub packages like it is recommended. In practice it'd look something like this:
```
include Css_Js_Core.Make({
  [@bs.module "@emotion/css"]
  external mergeStyles: (. array(string)) => string = "cx";

  [@bs.module "@emotion/css"] external make: (. Js.Json.t) => string = "css";

  [@bs.module "@emotion/css"]
  external injectRule: (. Js.Json.t) => unit = "injectGlobal";

  [@bs.module "@emotion/css"]
  external injectRaw: (. string) => unit = "injectGlobal";

  [@bs.module "@emotion/css"]
  external makeKeyFrames: (. Js.Dict.t(Js.Json.t)) => string = "keyframes";
});
type cache;

[@bs.module "@emotion/cache"] external cache: cache = "cache";
```
I quickly tested this by installing Emotion 11, bs-css 12 and used a custom `Css.re` (and not the one provided by `bs-css-emotion`). At least I was able to get some styles showing so it seems like an easy update.

I just wanted to bring this up so that it doesn't go unnoticed as it's something that could improve the DX for the people configuring dependencies and also makes updating to Emotion 11 quite tempting :)

**Comment by giraud** [comment]
Thanks for pointing that, I'm not following emotion dev closely. 
maybe you could do a PR that would be merged for a next major version ?

**Comment by idkjs** [comment]
@TomiS would you mind posting a gist of your custom `Css.re`? Maybe we can get into the next release as @giraud suggests? Thank you, sir.

**Comment by TomiS** [comment]
Hey, I made a PR to implement the changes. Unfortunately there are issues with the test app that probably require attention and unfortunately I don't have more time now. But I hope this helps a bit.

**Comment by idkjs** [comment]
@TomiS @giraud it is just two divs causing the problem. I figuring we just need to for the rule differently. I will try to chase it down later. Maybe take a quick look and see if anything jumps out at you guys.

**Comment by giraud** [comment]
thanks, I'll look at it next week
