### ISSUE TITLE
Rationale for CssJs uncurried functions?

### ISSUE THREAD

**Issue by TomiS** [reasonml-labs/bs-css#225]
Hey. I'm trying to convert some of our components to use `CssJs` module in ReScript syntax. I noticed all of the `CssJs` functions such as `style` are defined as uncurried and require the dot to be used when calling. I'm wondering if the requirement for uncurried is absolutely necessary (I don't know, I'm just asking), because the style function is used _a lot_ and every weird quirk (like requiring a dot) makes it that much more cumbersome to use. Also the type hint is ugly with uncurried functions.

**Comment by giraud** [comment]
I don't have the button to convert an issue to a discussion, so I copied it to https://github.com/reasonml-labs/bs-css/discussions/228.
