### ISSUE TITLE
`__tests_helpers__` must be listed as `"type": "dev"` in `sources` propety of `bsconfig.json`

### ISSUE THREAD

**Issue by entyo** [reasonml-labs/bs-css#237]
## What I have confirmed

0. Created a initial ReasonReact project by [`bsb -init my-react-app -theme react-hooks`](https://reasonml.github.io/reason-react/blog/2019/10/18/new-bsb-template)
1. Installed `"bs-css-emotion": "2.5.0"`
2. Listed up `bs-css` and `bs-css-emotion` on `"bs-dependencies"` property of `bsconfig.json`
3. Exited `yarn` and then `yarn bsb -make-world `

Got:

```
Dependency on reason-react
Dependency on bs-css
Error: /home/..../node_modules/bs-css/__tests_helpers__: No such file or directory
```

When I change `node_modules/bs-css/bsconfig.json` like this:

```
{
  "dir": "__tests_helpers__",
  "type": "dev"
}
```

I can make `yarn bsb -make-world ` work well.

**Comment by giraud** [comment]
oops, sorry, didn't think of that. fixed in bs-css@14.0.1 and bs-css-emotion@2.5.1
